version: '3'
volumes:
  caddy_data:
  caddy_config:
services:
  caddy:
    image: caddy
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - 80:80
      - 443:443
    command: caddy reverse-proxy --from ${NO_COAT_HOST} --to backend:8000 
  backend:
    build:
      context: .